### ISSUE TITLE
command line arguments for install on intel compiler

### ISSUE THREAD

**Issue by mjv500** [GkAntonius/ElectronPhononCoupling#3]
Hello,

it would be nice to add the following to the README.rst file somewhere: I had to specify the cc compiler explicitly for the python build

FC=ifort CC=icc CFLAGS="-I/softs/intel/compilers_and_libraries_2016.2.181/linux/mpi/intel64/include/" LDFLAGS="-L/softs/intel/compilers_and_libraries_2016.2.181/linux/mpi/intel64/lib -lmpi"  python ./setup.py install

probably the FC is not needed...

thanks!

Matthieu

**Comment by mjv500** [comment]
Re-update: the above compiles but does not work. You have to be careful to compile with the same CC that was used to generate the python itself (almost always gcc). There are ways around, but they are complex in the setup.py. Bottom line is: enforce CC=gcc, or whatever was used to make python. The communication with abinit is through netcdf files which are agnostic.

**Comment by GkAntonius** [comment]
I suppose the compiler environment variables are used to build the netCDF4 library. I've included your instructions in the README file.
